apiVersion: v1
kind: Service
metadata:
  name: nestjs-realword-example-app-service
  namespace: nestjs
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31000
  selector:
    app: nestjs-realword-example-app
    tier: be
