apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: nestjs
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
